entity.product.settings:
  title: 'Settings'
  route_name: entity.product.settings
  base_route: entity.product.settings
entity.product.view:
  title: 'View'
  route_name: entity.product.canonical
  base_route: entity.product.canonical
entity.product.edit_form:
  title: 'Edit'
  route_name: entity.product.edit_form
  base_route: entity.product.canonical
entity.product.delete_form:
  title: 'Delete'
  route_name: entity.product.delete_form
  base_route: entity.product.canonical
  weight: 10
entity.product.collection:
  title: 'Products'
  route_name: entity.product.collection
  base_route: system.admin_content
  weight: 10
