entity.product.settings:
  path: 'admin/structure/product/fields'
  defaults:
    _form: '\Drupal\product\Form\ProductSettingsForm'
    _title: 'Product'
  requirements:
    _permission: 'administer product'
