<?php

declare(strict_types=1);

/**
 * @file
 * Provides a product entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function product_theme(): array
{
  return [
    'product' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for product templates.
 *
 * Default template: product.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the product information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_product(array &$variables): void
{
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_entity_presave().
 */
function product_entity_presave(Drupal\Core\Entity\EntityInterface $entity)
{
  if ($entity->getEntityTypeId() == 'product' && $entity->hasField('field_product_of_the_day')) {
    if ($entity->field_product_of_the_day->value) {

      $productId = $entity->id();
      $query = \Drupal::entityTypeManager()
        ->getStorage('product')
        ->getQuery()
        ->accessCheck(TRUE)
        ->condition('field_product_of_the_day', TRUE)
        ->condition('id', $productId, '<>')
        ->count()
        ->execute();
      if ($query >= 5) {
        \Drupal::messenger()->addError('You cannot select more than 5 products as Product of the Day');
        $entity->set('field_product_of_the_day', FALSE);
      }
    }
  }
}

/**
 * Implements hook_schema().
 */
function product_schema()
{
  $schema['product_of_the_day'] = array(
    'description' => 'Stores click history on products of the day.',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'ID',
      ),
      'product_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Product ID',
      ),
      'created' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Timestamp of creation.',
      ),
    ),
    'primary key' => array('id'),
  );
  return $schema;
}
